// Gigs.js

// Define the gigs data as an array of objects
const productsData = [
    {
        id: "1",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIiIvdArzZ8R1nebaBZ1ymzqE-n01amFjM0g&s",
        jobTitle: "Perfume Rice",
        companyName: "Amazon Fresh",
        duration: "3 Days",
        rate: "₦ 2600",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Full time",
        category: "Development",
    },
    {
        id: "2",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIiIvdArzZ8R1nebaBZ1ymzqE-n01amFjM0g&s",
        jobTitle: "Jasmin Rice",
        companyName: "Google Foods",
        duration: "3 Days",
        rate: "₦ 2100",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part time",
        category: "Blockchain",
    },
    {
        id: "3",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIiIvdArzZ8R1nebaBZ1ymzqE-n01amFjM0g&s",
        jobTitle: "Vietnam Rice",
        companyName: "Facebook Farm",
        duration: "1 Days",
        rate: "₦ 2000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Contract",
        category: "Development",
    },
    {
        id: "4",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIiIvdArzZ8R1nebaBZ1ymzqE-n01amFjM0g&s",
        jobTitle: "Long Grain",
        companyName: "Jumbo Goods",
        duration: "2 Days",
        rate: "₦ 1000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "5",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCRLJeqv1Gzvl0qf2OHihh-AXGQ03vyOHLbw&s",
        jobTitle: "Fresh Onion",
        companyName: "Jumbo Goods",
        duration: "2 Days",
        rate: "₦ 1500",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "6",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCRLJeqv1Gzvl0qf2OHihh-AXGQ03vyOHLbw&s",
        jobTitle: "Fresh Onion",
        companyName: "Jumbo Goods",
        duration: "4 Days",
        rate: "₦ 4000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "7",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCRLJeqv1Gzvl0qf2OHihh-AXGQ03vyOHLbw&s",
        jobTitle: "Fresh Onion",
        companyName: "Celo",
        duration: "4 Days",
        rate: "₦ 5000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "8",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCRLJeqv1Gzvl0qf2OHihh-AXGQ03vyOHLbw&s",
        jobTitle: "Fresh Onion",
        companyName: "Celo",
        duration: "2 Days",
        rate: "₦ 1200",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "9",
        companyLogo: "https://cdn.punchng.com/wp-content/uploads/2018/09/26054809/tubers-of-yam.jpg",
        jobTitle: "Yam",
        companyName: "Celo",
        duration: "2 Days",
        rate: "₦ 2000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "10",
        companyLogo: "https://cdn.punchng.com/wp-content/uploads/2018/09/26054809/tubers-of-yam.jpg",
        jobTitle: "Yam",
        companyName: "Celo",
        duration: "4 Days",
        rate: "₦ 1500",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "11",
        companyLogo: "https://cdn.punchng.com/wp-content/uploads/2018/09/26054809/tubers-of-yam.jpg",
        jobTitle: "Yam",
        companyName: "Celo",
        duration: "4 Days",
        rate: "₦ 1000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "12",
        companyLogo: "https://wealthresult.com/wp-content/uploads/2015/02/Tomato.jpg",
        jobTitle: "Tomatoes",
        companyName: "Celo",
        duration: "4 Days",
        rate: "₦ 1800",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "13",
        companyLogo: "https://wealthresult.com/wp-content/uploads/2015/02/Tomato.jpg",
        jobTitle: "Tomatoes",
        companyName: "Wild Agro",
        duration: "2 Days",
        rate: "₦ 2000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "14",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO_YUhGb4iGB9tQK4dNsZLPINHAn8BC3yYgQ&s",
        jobTitle: "Chicken",
        companyName: "Wild Agro",
        duration: "2 Days",
        rate: "₦ 1000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "15",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO_YUhGb4iGB9tQK4dNsZLPINHAn8BC3yYgQ&s",
        jobTitle: "Chicken",
        companyName: "Wild Agro",
        duration: "4 Days",
        rate: "₦ 1900",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "16",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO_YUhGb4iGB9tQK4dNsZLPINHAn8BC3yYgQ&s",
        jobTitle: "Chicken",
        companyName: "Wild Agro",
        duration: "4 Days",
        rate: "₦ 1000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "17",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Wild Agro",
        duration: "4 Days",
        rate: "₦ 2000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "18",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Wild Agro",
        duration: "4 Days",
        rate: "₦ 3000",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "19",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2 Days",
        rate: "₦ 1200",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "20",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2 Days",
        rate: "₦ 1500",
        productDescription: "This product is awesome",
        quantity: "26",
        type: "Part-Time",
        category: "Ui/Ux",
    },
];

export default productsData;
